
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rherlkynqjzbcjdhromt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJoZXJsa3lucWp6YmNqZGhyb210Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg1OTAxODUsImV4cCI6MjA1NDE2NjE4NX0.rXiaaRAoW4mdpBoWiQ7YfhNgrpvtJ2AmKFUf8H_nwhw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  db: {
    schema: 'public',
  },
  auth: {
    autoRefreshToken: true,
    persistSession: true,
  },
});

// This is a workaround to inform TypeScript about the tables that exist
// in our Supabase database but aren't defined in the generated types.
// The actual runtime behavior is not affected by this workaround.
declare module '@supabase/supabase-js' {
  interface SupabaseClientOptions<SchemaName> {
    db: {
      schema: SchemaName;
    };
  }
}

export type Tables = {
  direct_messages: {
    id: string;
    sender_id: string;
    recipient_id: string;
    content: string;
    attachment_url: string | null;
    attachment_type: string | null;
    attachment_name: string | null;
    is_read: boolean;
    created_at: string;
  };
  user_follows: {
    id: string;
    follower_id: string;
    following_id: string;
    created_at: string;
  };
};
